apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: local-k8s-store
spec:
  provider:
    kubernetes:
      remoteNamespace: argocd
      auth:
        serviceAccount:
          name: eso-k8s-reader
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-k8s-reader