apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-k8s-read-buildkit
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-k8s-read-bind-buildkit
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: eso-k8s-reader
    namespace: buildkit-service
roleRef:
  kind: Role
  name: eso-k8s-read-buildkit
  apiGroup: rbac.authorization.k8s.io
