apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-k8s-read
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-k8s-read-bind
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: eso-k8s-reader
roleRef:
  kind: Role
  name: eso-k8s-read
  apiGroup: rbac.authorization.k8s.io
