kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  global:
    site: datadoghq.com
    kubelet:
      tlsVerify: false
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
      containers:
        agent:
          env:
            - name: DD_PROCESS_AGENT_ENABLED
              value: "true"
          volumeMounts:
            - name: passwd
              mountPath: /etc/passwd
              readOnly: true
      volumes:
        - hostPath:
            path: /etc/passwd
          name: passwd

  features:
    processCollection:
      enabled: true