apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-secret
  namespace: datadog-operator
spec:
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: datadog-secret  # 결과적으로 생성될 K8s Secret 이름
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: datadog
        property: api-key
    - secretKey: app-key
      remoteRef:
        key: datadog
        property: app-key
