apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecr-oci-auth
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: '{{metadata.annotations.addons_repo_url}}'
      targetRevision: '{{metadata.annotations.addons_repo_revision}}'
      path: '{{metadata.annotations.addons_repo_basepath}}additional_resources/addons/{{values.addonChart}}'
  destination:
    namespace: '{{metadata.annotations.external_secrets_namespace}}'
    name: '{{name}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
