apiVersion: builtin
kind: PatchTransformer
metadata:
  name: clusterrolebinding-syncwave
patch: |-
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "6"
target:
  kind: ClusterRoleBinding
