apiVersion: builtin
kind: PatchTransformer
metadata:
  name: customresourcedefinition-syncwave
patch: |-
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
target:
  kind: CustomResourceDefinition
