apiVersion: builtin
kind: PatchTransformer
metadata:
  name: customresourcedefinition-syncwave
patch: |-
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "2"
target:
  kind: CustomResourceDefinition
