apiVersion: builtin
kind: PatchTransformer
metadata:
  name: persistentvolumeclaim-syncwave
patch: |-
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "8"
target:
  kind: PersistentVolumeClaim
