apiVersion: builtin
kind: PatchTransformer
metadata:
  name: poddisruptionbudget-syncwave
patch: |-
  apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "9"
target:
  kind: PodDisruptionBudget
