apiVersion: builtin
kind: PatchTransformer
metadata:
  name: poddisruptionbudget-syncwave
patch: |-
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "9"
target:
  kind: PodDisruptionBudget
