apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: http://vault-alb-1205128207.ap-northeast-2.elb.amazonaws.com:8200
      path: secret  # KV Engine 이름
      version: v2
      auth:
        tokenSecretRef:
          name: vault-secret
          namespace: argocd
          key: token