apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-ecr-store
spec:
  provider:
    vault:
      server: 
        secretRef:
          name: in-cluster
          namespace: argocd
          key: vault_alb_url
      path: secret  # KV Engine 이름
      version: v1
      auth:
        tokenSecretRef:
          name: in-cluster
          namespace: argocd
          key: vault_token