apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agent
  - integrations

patches:
  - target:
      kind: DatadogAgent
      name: datadog
    patch: |-
      - op: add
        path: /spec/override/nodeAgent/extraConfd
        value:
          configMap:
            name: datadog-integrations-config
