apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-integrations-config
  namespace: datadog-operator
data:
  # vllm integration
  vllm.yaml: |
    init_config:
      timeout: 10
    instances:
      - openmetrics_endpoint: http://vllm-inference-server-qwen.vllm-prod.svc.cluster.local:8000/metrics
        service: vllm-inference-server-qwen
        tags:
          - env:prod
          - team:mlops
          - app:vllm-inference-server-qwen
  
  dcgm.yaml: |
    init_config: {}
    instances:
      - openmetrics_endpoint: http://nvidia-dcgm-exporter.gpu-operator.svc.cluster.local:9400/metrics
        service: nvidia-dcgm-exporter
        tags:
          - env:prod
          - team:mlops
          - app:nvidia-dcgm-exporter

  argocd.yaml: |
    init_config:
      service: argocd

    instances:
      - app_controller_endpoint: http://argocd-metrics:8082/metrics
        appset_controller_endpoint: http://argocd-applicationset-controller:8080/metrics
        api_server_endpoint: http://argocd-server-metrics:8083/metrics
        repo_server_endpoint: http://argocd-repo-server:8084/metrics
        tags:
          - service:argocd
          - team:mlops
          - env:prod
        min_collection_interval: 30