# Root key for MinIO Tenant Chart
tenant:
  pools:
    ###
    # The number of MinIO Tenant Pods / Servers in this pool.
    # For standalone mode, supply 1. For distributed mode, supply 4 or more.
    # Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: 2
      volumesPerServer: 2
      ###
      # The capacity per volume requested per MinIO Tenant Pod.
      # size: 10Gi
      storageClassName: directpv-min-io