service:
  type: NodePort
  ports:
    - name: http
      nodePort: 31129
      port: 9000
      protocol: TCP
      targetPort: 9000

secret:
  # If volume is already created in advance, then only name and metaurl is needed
  name: "juicefs-bucket"
  metaurl: "redis://redis-master.tenant.svc.cluster.local/1"  # URL of metadata engine
  storage: "minio"  # Object storage type (e.g. s3,
  accessKey: "minio"  # Access Key for object storage
  secretKey: "minio123"
  bucket: "http://myminio-hl.tenant.svc.cluster.local:9000/juicefs-bucket"  # A bucket URL to store data