apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-helm-oci-repo
  namespace: argocd
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: ecr-auth-generator
    kind: ClusterSecretStore
  target:
    name: ecr-helm-oci-repo
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: ecr-token-generated
        property: authToken
  template:
    type: Opaque
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repository
    data:
      type: helm
      name: ecr-helm
      url: 058264501230.dkr.ecr.ap-northeast-2.amazonaws.com
      enableOCI: "true"
      username: AWS
      password: "{{ .password }}"
