apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-token-generated
  namespace: argocd
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: ecr-auth-generator
    kind: ClusterSecretStore
  target:
    name: ecr-token-generated
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          name: ecr-auth-generator
          kind: ECRAuthorizationToken
