apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-helm-oci-repo
  namespace: argocd
  annotations:
    argocd.argoproj.io/tracking-id: >-
      addon-in-cluster-external-secrets:external-secrets.io/ExternalSecret:argocd/ecr-helm-oci-repo
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ecr-auth-generator
  target:
    name: ecr-helm-oci-repo
    creationPolicy: Owner
    template:  # ✅ 올바른 위치로 수정
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        enableOCI: 'true'
        name: ecr-helm
        password: '{{ .password }}'
        type: helm
        url: 058264501230.dkr.ecr.ap-northeast-2.amazonaws.com
        username: AWS
  data:
    - secretKey: password
      remoteRef:
        key: ecr-token-generated
        property: authToken
