apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: local-k8s-store
  namespace: ai-cell
spec:
  provider:
    kubernetes:
      remoteNamespace: argocd
      auth:
        serviceAccount:
          name: eso-k8s-reader
