apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-docker-config
  namespace: ai-cell
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: ecr-auth-generator
    kind: ClusterSecretStore
  target:
    name: ecr-docker-config
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .proxy_endpoint | trimPrefix `https://` }}": {
                "auth": "{{ .token }}"
              }
            }
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          name: ecr-auth-generator
          kind: ECRAuthorizationToken
